/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
   english: [
     'en/intro',
     'en/quick-start',
     'en/tutorial',
     {
      type: 'category',
      label: 'Connect a UI',
      link: {
        type: 'generated-index'
      },
      collapsed: true,
      items: [
        {
         type: 'autogenerated',
         dirName: 'en/connect-a-ui',
        }
      ]
     },
     {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'generated-index'
      },
      collapsed: true,
      items: [
        {
         type: 'autogenerated',
         dirName: 'en/integrations',
        }
      ]
     }, 
     {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index'
      },
      collapsed: true,
      items: [
        {
         type: 'autogenerated',
         dirName: 'en/guides',
        }
      ]
     },   
     {
       type: 'category',
       label: 'References',
       link: {
         type: 'generated-index'
       },
       collapsed: true,
       items: [
         {
          type: 'autogenerated',
          dirName: 'en/references',
         }
       ]
      },
      {
        type: 'category',
        label: 'FAQ',
        link: {
          type: 'generated-index',
        },
        collapsed: true,
        items: [
          {
           type: 'autogenerated',
           dirName: 'en/faq',
          }
        ]
       },
       {
        type: 'category',
        label: 'About Us',
        link: {
          type: 'generated-index'
        },
        collapsed: true,
        items: [
          {
           type: 'autogenerated',
           dirName: 'en/about-us',
          }
        ]
       },
    ], 
    // russia: [
    //   {
    //     type: 'autogenerated',
    //     dirName: 'ru',
    //    },
    //  ],
};

module.exports = sidebars;