/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
   english: [
     'intro',
     'quick-start',
     'tutorial',
     {
      type: 'category',
      label: 'Connect a UI',
      link: {
        type: 'generated-index'
      },
      collapsed: true,
      items: [
        {
         type: 'autogenerated',
         dirName: 'connect-a-ui',
        }
      ]
     },
     {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'generated-index'
      },
      collapsed: true,
      items: [
        {
         type: 'autogenerated',
         dirName: 'integrations',
        }
      ]
     }, 
     {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index'
      },
      collapsed: true,
      items: [
        {
         type: 'autogenerated',
         dirName: 'guides',
        }
      ]
     },   
     {
       type: 'category',
       label: 'References',
       link: {
         type: 'generated-index'
       },
       collapsed: true,
       items: [
         {
          type: 'autogenerated',
          dirName: 'en',
         }
       ]
      },
      {
        type: 'category',
        label: 'FAQ',
        link: {
          type: 'generated-index',
        },
        collapsed: true,
        items: [
          {
           type: 'autogenerated',
           dirName: 'faq',
          }
        ]
       },
       {
        type: 'category',
        label: 'About Us',
        link: {
          type: 'generated-index'
        },
        collapsed: true,
        items: [
          {
           type: 'autogenerated',
           dirName: 'about-us',
          }
        ]
       },
    ],
    russia: [
      {
        type: 'autogenerated',
        dirName: 'ru',
       },
     ],
};

module.exports = sidebars;